### ISSUE TITLE
Rationalising dbt script names

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-buildtools#125]
In the past few months, multiple "setup" scripts have been created with similar names and slightly different purposes - a good mix for confusion. Maybe it's worth thinking if we can rationalize the names of these scripts/functions and maybe the numbers

daq-buildtools scripts:
1. `dbt-setup-env.sh`  (in `daq-buildtools`):  loads the daq-buildtools basic environment
2. `dbt-setup-env.sh` (symlink in each work area): convenience link to the above
3. `setup_dunedaq.sh` (on `/cvmfs/dunedaq.opensciencegrid.org/`): defines the `setup_dbt` bash function
4. `setup_dbt` (function): shortcut for setting up dbt from `cvmfs`

daq work area scripts:
5. `dbt-setup-build-environment.sh` (from `daq-buildtools/scripts/`):  sets up the build environment in the local work area
6. `dbt-setup-runtime-environment.sh` (from `daq-buildtools/scripts/`): sets up the local work area runtime environment 

Some thoughts:
1. The `dbt-setup-` prefix feels a bit redundant. The script is in the top `dbt` directory already; it's nature and purpose it's pretty clear. How about `env.sh` or `setup.sh`?
2. Is this symlink actually useful? Assuming a positive answer, it could be renamed `dbt-env.sh` or `dbt-setup.sh` (I tend to prefer the former, but maybe it's just me);
3. `setup_dunedaq.sh` doesn't really setup much, compared to what other scripts do. In fact it just defines a function. What could be a good alternative name? 
4. `setup_dbt` too similar to 1.  and the name doesn't convey the information that its dbt-on-cmvfs. Suggestions for an alternative?
5. & 6.: These should be really merged, and maybe the name shortened a bit. E.g. `dbt-build-env`, maybe?

Comments, gentlemen! @jcfreeman2 @dingp

**Comment by jcfreeman2** [comment]
A couple of thoughts on the thoughts above: 
1. I can see the argument for renaming `dbt-setup-env.sh`. I'm totally fine either way, but here's one argument against the change: important daq-buildtools scripts and functions are all viewable in the shell after setup via `dbt-<tab>`, and as long as we retain the symlink referred to in point 2 above, you can cd into an existing work area and still hit `dbt-<tab>` to see the `dbt-setup-env.sh` script. 
2. I'm leaning against removing the symlink - though if we keep it, I should document its existence! I suppose the question is, if we remove the symlink, how often will people end up sourcing  a version of `dbt-setup-env.sh` which makes assumptions that no longer apply to an existing work area?
3. Don't really have a comment. 
4. Agree that `setup_dbt` should have a different name, but that's more in Pengfei's wheelhouse
5. and 6. , totally agree they should be merged given that `dbt-setup-runtime-environment` (1) is a superset of `dbt-setup-build-environment` which people frequently use, and (2) a common trap is for people to get confused about why they can't find executables, etc. since they didn't source `dbt-setup-runtime-environment`. Frankly, we can probably just use `dbt-setup-runtime-environment` as-is, and drop mention of `dbt-setup-build-environment` in our documentation. I agree we should change the name, though. Given that it's a script you need to re-source when you add and build a new repo to your work area, perhaps `dbt-update-env` or `dbt-refresh-env` or something along those lines would remind developers of the need to re-source the script.

**Comment by Juravenator** [comment]
might I also mention #120 which also attempts to simplify things by making them more familiar/predictable to people who have used other build tools.

**Comment by alessandrothea** [comment]
> A couple of thoughts on the thoughts above:
Thanks for the comments @jcfreeman2 

> 1. I can see the argument for renaming `dbt-setup-env.sh`. I'm totally fine either way, but here's one argument against the change: important daq-buildtools scripts and functions are all viewable in the shell after setup via `dbt-<tab>`, and as long as we retain the symlink referred to in point 2 above, you can cd into an existing work area and still hit `dbt-<tab>` to see the `dbt-setup-env.sh` script.

Right, I agree about 2. but the link and target don't need to have the same name :)
E.g.:
* `daq-buildtools.sh`: `env.sh`
* `<dev area>: `dbt-env.sh`

> 2. I'm leaning against removing the symlink - though if we keep it, I should document its existence! I suppose the question is, if we remove the symlink, how often will people end up sourcing a version of `dbt-setup-env.sh` which makes assumptions that no longer apply to an existing work area?

I do like the symlink, but I have been wondering whether people actually use it. And yes, it should be documented!
My assumption is that the version used for creating a development are is used during the whole lifecycle of the area itself.

> 5. and 6. , totally agree they should be merged given that `dbt-setup-runtime-environment` (1) is a superset of `dbt-setup-build-environment` which people frequently use, and (2) a common trap is for people to get confused about why they can't find executables, etc. since they didn't source `dbt-setup-runtime-environment`. Frankly, we can probably just use `dbt-setup-runtime-environment` as-is, and drop mention of `dbt-setup-build-environment` in our documentation. I agree we should change the name, though. Given that it's a script you need to re-source when you add and build a new repo to your work area, perhaps `dbt-update-env` or `dbt-refresh-env` or something along those lines would remind developers of the need to re-source the script.

Very good, very good. How long do you think it would take to merge the 2 scripts?
About the name, `dbt-update-env` and  `dbt-refresh-env` still seem a bit too similar to 2. How about `dbt-work-env` or similar? Where `work` refers to "work-area".

**Comment by alessandrothea** [comment]
> might I also mention #120 which also attempts to simplify things by making them more familiar/predictable to people who have used other build tools.

Hi @Juravenator , let me answer in #120
