### ISSUE TITLE
Investigate using spack rather than ups for package management

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#161]
With the dunedaq-v2.8.0 release behind us, we now have an opening to investigate using Spack for packaging rather than ups.

**Comment by jcfreeman2** [comment]
In the immediate term: Patricia's done a lot of work on proto-spack which has already packaged up our externals, and I'm looking into how to incorporate her efforts into the daq-buildtools system.

**Comment by brettviren** [comment]
https://github.com/DUNE-DAQ/dunedaq-spack

**Comment by jcfreeman2** [comment]
Thanks @brettviren . Hopefully Patricia had a chance to look at dunedaq-spack when she handled the externals; at any rate your `package.py`'s for appfwk, listrev and cmdlib will be useful moving forward.

**Comment by dingp** [comment]
Here are my findings when testing on the most recent commit f280bd4:

#### Using `dbt-setup-release` to set up `dunedaq-v2.10.1` and `N22-04-02`.

Both finished correctly. I have two comments, one about the message printed out by `dbt-setup-release` and the other about if we can allow `dbt-setup-release` to be run on another release without exit the current shell:

*  The message printed out after running `dbt-setup-release` including "Calling "spack load dunedaq@dunedaq-v2.10.1"; will print "Finished" when successfully done." I misread this in the beginning, overlooked the `;` in the sentence, and thought I will need to run `spack load dunedaq@dunedaq-v2.10.1` after calling `dbt-setup-release`, and expect `Finished` to be printed. Changing the printout "Finished" to "Successfully loaded `dunedaq@dunedaq-v2.10.1`" and the message itself to something like the following might help people like me: 
>`dbt-setup-release` is calling `spack load dunedaq@dunedaq-v2.10.1`. If this is the first time you've run this .... "Successfully loaded `dunedaq@dunedaq-v2.10.1`" will be printed after the release is successfully set up.

* `dbt-setup-release` sets up some ENV to flag if it's ever been run in this shell, exits if so. So if one wants to test on another release after running `dbt-setup-release` on one release, they would need to get a clean shell first. This is historically required by the UPS releases to guarantee a clean environment. But it may not be necessary any more. Checking if currently in a python venv and active spack env (`spack env status`) might be enough here. Technically doing `deactivate` (exit the python virtual environment) and then `despacktivate` (exit the spack environment) should be enough to ensure a clean environment before running `dbt-setup-release` on another release.
 
#### Using `dbt-create.py` to create a work area based on the nightly release `N22-04-02` in cvmfs.

* I found that `dbt-create.py` expects `python 3.8.3` in the system. Not sure if this is too strict. Though, I tested with system python on `np04-srv-018`, which is `python3.6`. It has no issues with listing the available releasees, but got errors like the following when creating a local work area.

```bash
[pding@np04-srv-018 daq-buildtools]$ dbt-create.py -n -c  N22-04-02 ../dev-n22-04-02
Traceback (most recent call last):
  File "/scratch/dingpf/daq-buildtools/bin/dbt-create.py", line 14, in <module>
    exec(open('{}/scripts/dbt_create.py'.format(DBT_ROOT)).read())
  File "<string>", line 87, in <module>
  File "/scratch/dingpf/daq-buildtools/scripts/dbt_setup_tools.py", line 44, in get_time
    return subprocess.run(dateargs, capture_output=True).stdout.decode("utf-8").strip()
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
[pding@np04-srv-018 daq-buildtools]$ cd ..
[pding@np04-srv-018 dingpf]$ dbt-create.py -n -c  N22-04-02 dev-n22-04-02
Traceback (most recent call last):
  File "/scratch/dingpf/daq-buildtools/bin/dbt-create.py", line 14, in <module>
    exec(open('{}/scripts/dbt_create.py'.format(DBT_ROOT)).read())
  File "<string>", line 87, in <module>
  File "/scratch/dingpf/daq-buildtools/scripts/dbt_setup_tools.py", line 44, in get_time
    return subprocess.run(dateargs, capture_output=True).stdout.decode("utf-8").strip()
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

But after swtiching to `python3.8.3` in the spack externals instance, `dbt-create.py` successfully create my local work area.

* ✔️ My work area looks like:

```bash
[pding@np04-srv-018 dingpf]$ tree -L 2 ./dev-n/
./dev-n/
├── build
├── dbt-env.sh -> /scratch/dingpf/daq-buildtools/env.sh
├── dbt-pyvenv
│   ├── bin
│   ├── include
│   ├── lib
│   ├── lib64 -> lib
│   ├── LICENSE
│   ├── pyvenv.cfg
│   └── share
├── dbt-workarea-constants.sh
├── log
└── sourcecode
    ├── CMakeGraphVizOptions.cmake
    ├── CMakeLists.txt
    └── dbt-build-order.cmake

9 directories, 7 files
```

* ✔️ And the new `dbt-workarea-constants.sh` has the following contents:

```bash
[pding@np04-srv-018 dev-n]$ cat /scratch/dingpf/dev-n/dbt-workarea-constants.sh
export DBT_DUNE_DAQ_BASE_RELEASE="N22-04-02"
export SPACK_RELEASES_DIR="/cvmfs/dunedaq-development.opensciencegrid.org/sandbox/spack-nightly"
export DBT_AREA_ROOT="/scratch/dingpf/dev-n"
export DBT_ROOT_WHEN_CREATED="/scratch/dingpf/daq-buildtools"
```

* ✔️ `source dat-env.sh` and `dbt-workarea-env` also worked as expected after I logged out and logged back in.
* ✔️  I tested `dbt-build.py` on building `appfwk`. I had some observations on the output (brought in by newer CMake), which are the same as those posted [here](https://github.com/DUNE-DAQ/daq-release/issues/130#issuecomment-1089263335).
* ✔️ The `--lint` and `--unittest` option with `dbt-build.py` also worked.
* ✔️ Running `dbt-workarea-env` after `dbt-build.py` updated the paths to include newly installed `appfwk` in the working area, and `which daq_application` showed the one in the local work area is chosen.
* `dbt-workarea-env --refresh` worked as expected, but might be improved. `spack unload <pkg>` can be replaced by `despacktivate`. This is to exit the spack environment, which effectively unloads all spack packages. This is more robust since one might load additional spack packages or different versions of packages.

#### Using `dbt-create.py` to create a work area using release configuration directory in `daq-release/configs` from the `daq-release` repo.

This is not working yet. It expects the release area with a spack instance exits on cvmfs. This is different than the feature using UPS releases/products. We shall think about how this feature should evolve under spack, or simply no longer support this feature under spack.


```bash
[pding@np04-srv-018 dingpf]$ dbt-create.py -r daq-release/configs dunedaq-v2.10.1 dev-2101
Setting up the Python subsystem.
Please be patient, this should take O(1 minute)...
stdout from /scratch/dingpf/daq-buildtools/scripts/dbt-create-pyvenv.sh /scratch/dingpf/daq-release/configs/dunedaq-v2.10.1/pyvenv_requirements.txt:

stderr from /scratch/dingpf/daq-buildtools/scripts/dbt-create-pyvenv.sh /scratch/dingpf/daq-release/configs/dunedaq-v2.10.1/pyvenv_requirements.txt:
ERROR: [04/07/22 06:35:45] [dbt-setup-tools.sh:196]:  Unable to find Spack setup script "daq-release/configs/dunedaq-v2.10.1/spack-0.17.1/share/spack/setup-env.sh"

ERROR: [Thu Apr  7 06:35:45 CEST 2022] [<string>:154]: There was a problem running "/scratch/dingpf/daq-buildtools/scripts/dbt-create-pyvenv.sh /scratch/dingpf/daq-release/configs/dunedaq-v2.10.1/pyvenv_requirements.txt" (return value 100); exiting...

```

#### Non-directly related issues found during the test

* After loading the `python v3.8.3` from spack externals instance, the system git failed when cloning a repo. The error message is the following. I think I understand the issue. `spack externals` uses a newer `krb5` lib, which was required (as shown in [this comment](https://github.com/DUNE-DAQ/daq-release/pull/128#issuecomment-1084604154)). But the system `git` is built with the older system `krb5`. We will need to find a solution for this, likely including `git` in the externals. After issuing a `spack unload --all`, the `git clone` finished correctly.

```bash
[pding@np04-srv-018 dingpf]$ git clone https://github.com/DUNE-DAQ/daq-release -b dingpf/spack-release
Cloning into 'daq-release'...
/usr/libexec/git-core/git-remote-https: symbol lookup error: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b

```

* `--lint` option with `dbt-build.py` worked. But it is using `clang` from UPS. Before the retirement of UPS, we will need to have `clang` (spack package `llvm`) included in the externals instance.

**Comment by dingp** [comment]
I have another finding about `git clone` failure after loading `python 3.8.3` from spack. `git clone` finished correctly inside the spack environment, and with the `dunedaq` package loaded. 

I think I got to the bottom of the issue now. The troubling piece here is the `openssl` and `krb5` version mismatch.

When loading `python 3.8.3` only, it loads `openssl@1.1.1l` as a dependency but not `krb5`. `openssl@1.1.1l` is not backward compatible with the system `openssl@1.1.1b`. `krb5` from the system cannot work with `openssl` from spack. 

Loading `dunedaq` umbrella package brings in both `openssl` and `krb5` as its dependencies. 

I think the solutions here could be either:
1. add `git` into the externals instance, built with openssl and krb5 in spack, and set up this `git` when setting up dbt.
2. when suggesting users to do `spack load python@3.8.3%gcc@8.2.0`, warning users about `git` might fail before doing `dbt-workarea-env` (that's when `krb5` is loaded by `dunedaq` umbrella package). The work-around (doing `spack unload --all`, then `git clone`, then load the python 3.8.3) might be too complicated to mention.

**Comment by jcfreeman2** [comment]
Based on Pengfei's input here and the discussion we had with Alessandro at this morning's Software Coordinator's Meeting, I've made a couple of changes to the branch. As always, instructions for testing it are [here](https://github.com/DUNE-DAQ/daq-buildtools/blob/johnfreeman/issue161_spack/docs/README.md). 

Changes include:
-Renaming `DBT_DUNE_DAQ_BASE_RELEASE` to `SPACK_RELEASE`
-Making the output when a spack package is loaded a little clearer
-Removing the `--refresh` option from `dbt-workarea-env`

**Comment by dingp** [comment]
Thanks for the quick turn-around. I verified all the changes.

I also noticed that the `spack env activate <ENV_NAME> -p` has been used after the changes. My shell prompt now has the spack ENV in front of it. It now looks like:

```bash
(dbt-pyvenv) [N22-04-02]  [pding@np04-srv-018 dev-0402]$
```

**Comment by dingp** [comment]
Updated the feature branch with the following:

1. 17d366a64a7592215de332ad5c377cd67755ef77 update paths pointing to `sandbox` to production deployment;
2. e285de7d70b904a36a0e44d80cc523fb901fadff use the symlink `space-installation` to `spack-0.17.1`, so that it's forward compatible if upgrading to a new spack version;
3. c1e08ad01fdabec232d1506783325d81e183391f `dbt-create.py` is now compatible with python>=3.6
4. 0198652e2ba3e670abd6958bef62b8868a4fc6be during my test, I found `dbt-workarea-env` will exit the python venv if running for a second time. It turns out that the `spack_setup_env` is causing this. This commit moved the `spack_setup_env` call to be inside the block executed when the script was run for the first time.

**Comment by jcfreeman2** [comment]
I've tested that all of Pengfei's changes work. Additionally, I've updated the documentation, in particular to include a section "Finding Info on Your Work Area" which tells users how to find the versions of the packages their repos will build against.
