### ISSUE TITLE
Can't build in Spack environment if llvm has been loaded

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/daq-buildtools#214]
With the steps listed below, I get errors when I try to build.  I believe that the problem is the `spack load llvm` line.  My sense is that this is a new problem, and I previously *could* successfully build with `llvm` loaded.  (I load `llvm` into my environment at the suggestion of Pengfei in order to get access to `clang-format`.

```
source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
setup_dbt latest-spack
dbt-create -c -n N22-05-25 25MayDevTest
cd 25MayDevTest/sourcecode
git clone https://github.com/DUNE-DAQ/daqconf.git -b develop
git clone https://github.com/DUNE-DAQ/dfmodules.git -b develop
cd ..
dbt-workarea-env
spack load llvm
dbt-build -j 16
```

**Comment by jcfreeman2** [comment]
I can't speak to whether this did or didn't work previously, but if I try your steps on `mu2edaq` what happens is that instead of using `gcc` the build system will instead use `clang` to try to build the code, which proceeds to fail. As a side project earlier this spring I _did_ get the codebase to compile, but among other things it required a couple of adjustments to `TRACE`, otherwise the failure is expected.

**Comment by bieryAtFnal** [comment]
Closing this Issue and opening a different one to ask for the ability to get access to clang-format without switching from gcc to clang for compiling...
