### ISSUE TITLE
it would be great to get access to clang-format in my software area without using clang for compiling

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/daq-buildtools#217]
A while ago, I asked for guidance on how to get access to the `clang-format` command in a Spack-based software area.  I was told to use `spack load llvm`.
However, with John's help, I now realize that `spack load llvm` switches the default compiler form gcc to clang.  I don't want that, of course.
So, I'd like to ask again for guidance on how to get access to `clang-format`, this time with the condition that I can still use gcc for compiling.

**Comment by dingp** [comment]
I think dbt should provide a wrapper to run clang-format so that the llvm is only loaded in sub-shells, and the default compiler can remain unchanged.
________________________________
From: bieryAtFnal ***@***.***>
Sent: Wednesday, May 25, 2022 11:39:31 AM
To: DUNE-DAQ/daq-buildtools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DUNE-DAQ/daq-buildtools] it would be great to get access to clang-format in my software area without using clang for compiling (Issue #217)


A while ago, I asked for guidance on how to get access to the clang-format command in a Spack-based software area. I was told to use spack load llvm.
However, with John's help, I now realize that spack load llvm switches the default compiler form gcc to clang. I don't want that, of course.
So, I'd like to ask again for guidance on how to get access to clang-format, this time with the condition that I can still use gcc for compiling.

**Comment by jcfreeman2** [comment]
Agreed, I just posted a PR which does this. Basically we just hadn't ever Spackified `dbt-clang-format.sh` and having `spack load llvm` called explicitly at the commandline was a workaround since the script will use `clang-format` without any UPS-based action if it can find it.
