### ISSUE TITLE
Confusing list/dbt-create command for candidate release

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/daq-buildtools#225]
I can do this to list :
```
[np04daq@np04-srv-024 dunedaq]$ dbt-create -b candidate -l
 - rc-dunedaq-v2.11.1-1
 - rc-dunedaq-v3.0.0-1
 - rc-dunedaq-v3.0.0-2
 - rc-dunedaq-v3.0.0-3
 - rc-dunedaq-v3.0.0-4
 - rc-dunedaq-v3.0.0-5
 - rc-dunedaq-v3.1.0-1
 - rc-dunedaq-v3.2.0-1
```

but then when I try to use that output in a dbt-create, I get this:
```
[np04daq@np04-srv-024 dunedaq]$ dbt-create -b candidate rc-dunedaq-v3.2.0-1 dunedaq-v3.2.0-candidate-1
ERROR: [Tue Sep 27 12:06:51 CEST 2022] [<string>:86]: 
Release path
"/cvmfs/dunedaq-development.opensciencegrid.org/candidates/rc-dunedaq-v3.2.0-1"
does not exist. Note that you need to pass "-n" for a nightly build or "-b candidate"
for a candidate release build. Exiting...
```

where, I guess instead I'm supposed to use `rc-v3.2.0-1` without the dunedaq. Is there a reason that the list should give something different than what I'm supposed to use as an argument for base release? If not, can that be fixed?

**Comment by jcfreeman2** [comment]
Do you have the exact set of commands which led you to this result? Because I tried logging onto np04-srv-024 as jofreema, and the following worked out:
```
source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
setup_dbt dunedaq-v3.1.1
dbt-create -b candidate -l  # Yields same output you saw
dbt-create -b candidate rc-dunedaq-v3.2.0-1 dunedaq-v3.2.0-candidate-1  # Works
```

**Comment by jcfreeman2** [comment]
Also, concerning your "I'm supposed to use `rc-v3.2.0-1` without the dunedaq": it's true that testing with gcc 12 is preferable to testing with gcc 8, but your listing above suggests you set up the daq-buildtools which works with gcc 8. For details on what I'm talking about, see the note at the top of https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-buildtools/

**Comment by wesketchum** [comment]
ah, I could have sworn I had done it with gcc12 ... 

But ok, now that I do it with gcc12, I think that it looks ok:
```
[wketchum@np04-srv-024 dunedaq]$ dbt-create -b candidate -l
 - rc-v3.2.0-1
 ```

Though, I'm confused as to why when I did `dbt-create -b candidate rc-dunedaq-v3.2.0-1 dunedaq-v3.2.0-candidate-1` previously it did not work ...

Maybe this got fixed in the latest dbt update?

**Comment by jcfreeman2** [comment]
Interestingly enough: whereas the result of `dbt-create -b candidate -l` suggested you were using the `gcc 8.2.0`-friendly daq-buildtools (our classic `v5.0.9`, aka `dunedaq-v3.1.1`, aka `dunedaq-v3.0.0`, the second result where `/cvmfs/dunedaq-development.opensciencegrid.org/candidates/` wasn't found suggests you were using the `gcc 12.1.0`-friendly daq-buildtools since it was looking in the area for `gcc 12.1.0`-based releases as opposed to `gcc 8.2.0`-based releases (`/cvmfs/dunedaq-development.opensciencegrid.org/candidate-releases/`)

If you encounter a problem again, could you save as much info as possible about what you did in order for me to recreate the issue?

**Comment by wesketchum** [comment]
I haven't reproduced this in recent work, and so while I'm not sure what the issue was, I'm going to close this issue and open a new one /reopen this one if it reappears.
