### ISSUE TITLE
Look for ways to reduce boilerplate in CMakeLists.txt

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#27]
Brett and Alessandro both like the idea of having the build system make assumptions about what to do based on the names of files and the directories they're located in. There are common patterns which are emerging as new code is developed which we can take advantage of. E.g., DAQ components (DAQ modules, command facilities) tend to have names like `appfwk_QueryResponseCommandFacility_duneCommandFacility` , i.e., `<packagename>_<label><component type>_dune<component type>`). It would be nice to automate their naming. Or, if a source file contains "DAQModule", assume it's a DAQ module and automatically link in appfwk::appfwk.

**Comment by jcfreeman2** [comment]
I'll provide some thoughts in the next post, but first I think it would be illustrative to print Brett's original email to myself and Pengfei here:
```
Hi guys,

The recent "educational program" discussion in #104 makes me wonder
something.

At one point I thought we settled on mapping "semantically meaningful"
file system patterns onto build patterns.

Eg:

- each apps/*.cpp is a main() built and installed to <prefix>/bin/

- all src/*.cpp build to a .so installed to <prefix>/lib/

- the include/<pkg>/ installs to <prefix>/include/<pkg>/

- each plugin/*.cpp builds to an individual plugin .so

- ... etc ...

(Above are just examples.  The exact patterns of course would need some
development.)

I think the very explicit CMake rules we have now are an excellent
low-level explicit layer on which to implement this higher "semantic"
layer.  The benefit is that our CMakeList.txt files can become just a
few lines.  Corner cases can still be handled by using the lower-layer
explicit CMake functions.


Is this approach still planned?

-Brett.
```

**Comment by jcfreeman2** [comment]
Now, here are a couple of thoughts on what possibly-intelligent defaults might be.

* **Contents of the src/ directory**
If you look at appfwk, you'll see that there's a library of the same name as the package which is made up of a subset of the *.cpp files in src/. You'll also see a library "appfwk_QueryResponseCommandFacility_duneCommandFacility" built off of QueryResponseCommandFacility.cpp. Finally, things get a bit complicated as there's a file, FanOutDAQModule.cpp.in, which needs CMake to substitute in variables before it compiles; for the purposes of this discussion we can just focus on the post substitution C++ files created (VectorIntFanOutDAQModule.cpp, etc.)
One thing you'll notice is that all *.cpp files in src/ are either (A) compiled into the appfwk library, or (B) used to make some type of plugin, whether a DAQ Module or a Command Facility. So one idea would be to formalize this pattern: cpp files which contain some magic token, like "DAQModule" or "CommandFacility" will be understood to be intended to create plugin libraries, and all other cpp files in src/ will be used to create a library named after the package itself. 

* **Installation rules**
As Brett said, anything in apps/ gets automatically installed in <prefix>/bin. The plugins and package shared object library created in src/ get automatically installed in <prefix>/lib. It's already the case that all *.hpp and *.hxx files in include/ get copied to the installation subdirectory of the same name. 

* **Default linking**
Another idea (which may be more trouble than its worth) is to make sure that certain targets always get certain libraries linked in. E.g., all libraries/plugins within a package always get the package's main library linked in (so all the DAQ Modules, etc., in appfwk get appfwk automatically linked in). Or all executables always get Boost's program options library linked in. To satisfy this rule, you could use "daq_add_executable" or "daq_add_library", and if you were sure you didn't want the default linkages, you could revert to the classic CMake "add_executable" and "add_library" functions. However: I said this may be more trouble than its worth because the price of this convenience is that it's less transparent to someone inspecting the CMake code what, exactly, is happening to the targets. Furthermore, it means that certain DUNE DAQ CMake functions would rely on certain packages (though to be fair, this is already the case with daq_add_unit_test, which needs Boost)

**Comment by alessandrothea** [comment]
Hi John,

Your analysis looks sensible. Let me add a couple of other observations:

* Source code types: sticking with `appfwk` as working example, we can summarise the content as
  - library code: this uncontroversially contains what is meant to be provided as a shared library with the same name as the package
  - plugins: code, set of `*.cpp` which is built in a matching set of shared objects. Things get tricky here are the number of plugin types is unknown, a priori. The DAQModule plugins are expect to play a central role, but we have another type `CommandFacility` and more will follow. I like your suggestion, but my suggestion would be to use the file name in some clever, rather than a predefined (set of) magic token(s). For instance, assuming all plugin source `.cpp`s to be located in `plugins/` one could imagine:
     * Build each file in `libappfwk_<cpp basename>.so`. The developer is responsible to include the plugin type in the filename:  
    `QueryResponseCommandFacility_duneCommandFacility.cpp` -> `appfwk_QueryResponseCommandFacility_duneCommandFacility.so`  
Clearly many good opportunities for typos and mistakes here but hey, it's a tough life all around.
     * or trying to be slightly smarter, requiring the files in plugins to comply with a stricter pattern: `appfwk_<basename>_DAQModule.cpp` -> `libappfwk_<basename>_DAQModule.so`  

    whatever way is chosen, at this stage I would recommend something simple, which may not be perfect and allow some human error, but allow to gather experience and can be refined later.
  - others: specifically `FanOutDAQModule.cpp.in`. This doesn't really belong to `appfwk`, but to some sort of utility package. It was kept in `appfwk` v1 out of convenience, but it shouldn't be there by v2. Also, its case should be reviewed together with moo's integration #25.

* Installation rules: is it worth considering a `plugins` target installation for plugins?

* Default linking: I would defer this discussion to later, after having had a preview of what the new CMakelist.txt will look like and gather a bit of experience with it.

**Comment by alessandrothea** [comment]
Alight, it turns out that 'linking' (or rather dependencies of different targets) is kind of a fundamental issue to deal with, as @jcfreeman2 pointed out.

In a scenario where all the targets belonging to the same file system patter share the dependencies, yes, then appropriate cmake pattern-based functions would be able to automatically generate the packages targets based on the content of its subdirectory (this is what I had in mind in the first place). A look at `appfwk/CMakeLists.txt` was a good reminder of the need for different applications/plugins/etc to have a different set of dependencies: usually there will be extra dependencies, but cases where an utility app does not depend on the mail library should not be excluded.

In order to get a feeling of your concerns about possible `daq_add_xyz` wrappers, I tried to implement a few, to see how CMakeList files would look, and how obscure the function code would result. The result of this attempt is described below. Comments welcome!

**Details**
* A function to add the "package" library: 
  `daq_add_library(libname [SHARED/STATIC] sources [LINK_LIBRARIES libraries])`
  that replaces `add_library`+`target_link_libraries ` + `target_include_directories` calls. 
  It assumes that sources are located in the `src/` folder and libname = packagename.
   - This is not a fundamental choice, but rather a simple starting point.
   - `sources` and be a glob expression (e.g. `*.*`). Not crucial, something interesting to try
   - `LINK_LIBRARIES`: list of linked targets

* a function to add plugins:
  `daq_add_plugin( pluginname plugintype [TEST] [LINK_LIBRARIES libraries])`
  This function tries to standardise the declaration of plugins, which have slightly different requirements from the main library. It assumes the plugin code to be located in `plugins/`
  - There are multiple plugins per packages
  - The name of the plugin library must have the format
     `lib<package>_<pluginname>_<plugintype>.so`
    Up so far plugins have been made out of a single file which matches the plugin name, so `daq_add_plugin` derives the source code name and location from `pluginname` (again, not a fundamental choice, just a try)
   - `LINK_LIBRARIES`: list of linked targets
   - if `TEST` flag is set, the function expects the plugin code to be in `test/` and installs it in `tests/` as well.

* a function to add applications:
   `daq_add_application( appname [TEST] [LINK_LIBRARIES libraries] )`
  This is probably the simplest wrapper. `LINK_LIBRARIES` and `TEST` have the same meaning as above

This is how the `toylibrary` `CMakefiles.txt` looks like using these functions

```cmake
# Note that when the ers library is linked in, it uses a "::" because
# it's in an external package, not a local CMake target. The semantics
# are <namespace>::<shared library / executable>
daq_add_library(SHARED IntPrinter.cpp LINK_LIBRARIES ers::ers)

##############################################################################
daq_add_application( toylibrary_test_program toylibrary_test_program.cxx TEST LINK_LIBRARIES ${Boost_PROGRAM_OPTIONS_LIBRARY} toylibrary )

##############################################################################
daq_add_unit_test(ValueWrapper_test)
```

Previous version: https://github.com/DUNE-DAQ/daq-buildtools/blob/develop/toylibrary/CMakeLists.txt

A more interesting example is 

```cmake

##############################################################################
# Main library
daq_add_library(SHARED *.* LINK_LIBRARIES ${CETLIB} ${CETLIB_EXCEPT} ers::ers Folly::folly nlohmann_json::nlohmann_json pthread)

##############################################################################
# Plugins
daq_add_plugin(QueryResponseCommandFacility duneCommandFacility LINK_LIBRARIES appfwk)

# ##############################################################################
# Applications
daq_add_application( daq_application daq_application.cxx LINK_LIBRARIES appfwk )

# ##############################################################################
# # (No action taken, doc/ doesn't yet contain anything)

# ##############################################################################
# Test plugins
daq_add_plugin( DummyModule duneDAQModule TEST LINK_LIBRARIES appfwk )
daq_add_plugin( FakeDataConsumerDAQModule duneDAQModule TEST LINK_LIBRARIES appfwk )
daq_add_plugin( FakeDataProducerDAQModule duneDAQModule TEST LINK_LIBRARIES appfwk )

# Test applications
daq_add_application( queue_IO_check queue_IO_check.cxx TEST LINK_LIBRARIES appfwk )
daq_add_application( dummy_test_app dummy_test_app.cxx TEST LINK_LIBRARIES appfwk )

file(COPY test/producer_consumer_dynamic_test.json DESTINATION test)
```
Note: the FanoutModule macro has been commented out because it doesn't really belong here and needs to be moved elsewhere.

Previous version here: https://github.com/DUNE-DAQ/appfwk/blob/develop/CMakeLists.txt

**Comment by alessandrothea** [comment]
Something I forgot to add: 
In terms of transparency, these functions are sufficiently simple to locate and interpret, so I don't think transparency is going to be a problem.

**Comment by jcfreeman2** [comment]
@alessandrothea These functions look pretty good to me. Just a couple of comments:
* In your `daq_add_library` example, using a wildcard "\*.\*" would typically open us up to the glob problem where CMake skips config+generate even when a new sourcefile is added, but if I understand correctly from your exchange with Pengfei, there's a workaround for this in newer versions of CMake?
* A drawback of no longer requiring the user to explicitly spell out the target name but rather, having it deduced (e.g., not writing out `appfwk_FakeDataConsumerDAQModule_duneDAQModule`) is that whoever calls `daq_install` currently would need to figure out what the deduced target name is
* Probably goes without saying, but it would be nice to add checks in these functions where they get upset if they can't find the source file whose name they deduce. Less easy to implement but still useful would be if they could guess that a user incorrectly named a file (e.g., `FakeDataConsumerDAQmodule_duneDAQmodule.cpp` instead of `FakeDataConsumerDAQModule_duneDAQModule.cpp` ) and alert them to the mistake
* If using LINK_LIBRARIES is the way to tell `daq_add_library`, etc., what libraries to link in, then for consistency's sake I should use this in `daq_add_unit_test`
* In response to your "these functions are sufficiently simple to locate and interpret" - this is the case now while daq-buildtools is cloned in repo form and the path to `DAQ.cmake` explicitly printed, but this will be less the case when we switch to `find_package(daq-buildtools)` and still less the case when we stop cloning daq-buildtools into each user's development area. Something to keep in mind.

**Comment by alessandrothea** [comment]
Thanks for the comments John.
Answers inline

> * In your `daq_add_library` example, using a wildcard "*.*" would typically open us up to the glob problem where CMake skips config+generate even when a new sourcefile is added, but if I understand correctly from your exchange with Pengfei, there's a workaround for this in newer versions of CMake?

Yes, this is what I gather. The `CONFIGURE_DEPENDS` flag makes cmake aware that the glob has to be re-evaluated at every call. This is working for the top-level CMakeFile.

> * A drawback of no longer requiring the user to explicitly spell out the target name but rather, having it deduced (e.g., not writing out `appfwk_FakeDataConsumerDAQModule_duneDAQModule`) is that whoever calls `daq_install` currently would need to figure out what the deduced target name is

Correct, so in the current model where targets are created and installed in different calls deducing the target name is awkward. On the other hand having wrapper functions opens the option to delegate the installation to the wrapper.
This is something I wanted to discuss with you before making any concrete proposal. I had a look at the `daq_install` function but I haven't really understood how it does what it does 😅 

> * Probably goes without saying, but it would be nice to add checks in these functions where they get upset if they can't find the source file whose name they deduce. Less easy to implement but still useful would be if they could guess that a user incorrectly named a file (e.g., `FakeDataConsumerDAQmodule_duneDAQmodule.cpp` instead of `FakeDataConsumerDAQModule_duneDAQModule.cpp` ) and alert them to the mistake

Yep, agreed. 

> * If using LINK_LIBRARIES is the way to tell `daq_add_library`, etc., what libraries to link in, then for consistency's sake I should use this in `daq_add_unit_test`

Yep, that I did in the branch for internal consistency.

> * In response to your "these functions are sufficiently simple to locate and interpret" - this is the case now while daq-buildtools is cloned in repo form and the path to `DAQ.cmake` explicitly printed, but this will be less the case when we switch to `find_package(daq-buildtools)` and still less the case when we stop cloning daq-buildtools into each user's development area. Something to keep in mind.

Alright, but surely we will provide documentation detailing what they do, and a pointer to the repository in case people crave for the gory cmake details, won't we? :)

**Comment by jcfreeman2** [comment]
Concerning daq_install: it's a wrapper around
```
install(TARGETS ${DAQ_INSTALL_TARGETS} EXPORT ${exportset} )
install(EXPORT ${exportset} FILE ${exportset}.cmake NAMESPACE ${PROJECT_NAME}:: DESTINATION ${cmakedestination} )
```
where the first call tells CMake the targets we want to install, and the second actually writes them into a file (e.g., appfwkTargets.cmake). In order for installation to occur behind the scenes, ideally we'd want `install(TARGETS ...)` to be cumulative, i.e., this function would be called for each `daq_add_application`, etc., and then at the end of the CMakeLists.txt `daq_install` would skip the `install(TARGETS ...)` call and jump straight to `install(EXPORT ...)`. If it's not cumulative, then we'd want to make the DAQ_INSTALL_TARGETS list variable be global to the CMakeLists.txt file, and keep adding each new target to that variable for each `daq_` call. Either way, at the end, we could have `daq_install` take no arguments, and just export all the targets which had accumulated over the course of the CMakeLists.txt file into `<packagename>Targets.cmake`. 

Details on install can be found in https://cmake.org/cmake/help/v3.17/command/install.html

**Comment by alessandrothea** [comment]
Thanks for the explanation. I'm not sure I fully understand what you mean with cumulative. Can you briefly elaborate?

**Comment by jcfreeman2** [comment]
Sure. Imagine if, in the course of the CMakeLists.txt code executing, we have the following:
```
install(TARGETS app1 EXPORT johnspackageTargets)
install(TARGETS app2 EXPORT johnspackageTargets)
install(EXPORT johnspackageTargets FILE johnspackageTargets.cmake NAMESPACE johnspackage:: DESTINATION /johns/favorite/installation/area/cmake)
```
If install() is cumulative, then I'd expect app1 and app2 to both get installed. If install isn't cumulative, then I'd expect only app2 to get installed.

**Comment by alessandrothea** [comment]
Got it, thanks.
I've done a couple of tests and the export seems to be cumulative.
An example of `daq_*` functions and the modified `install` is here:

 https://github.com/DUNE-DAQ/daq-buildtools/blob/thea/i27-boilerplate-wrapper-demo/cmake/DAQ.cmake

**Comment by brettviren** [comment]
Hi @alessandrothea.  Please note:

``` cmake
  set(CMAKE_PREFIX_PATH ${CMAKE_SOURCE_DIR}/../build ${CMAKE_SOURCE_DIR}/../install )

  set(CMAKE_INSTALL_LIBDIR ${PROJECT_NAME}/${CMAKE_INSTALL_LIBDIR})
  set(CMAKE_INSTALL_BINDIR ${PROJECT_NAME}/${CMAKE_INSTALL_BINDIR})
  set(CMAKE_INSTALL_INCLUDEDIR ${PROJECT_NAME}/${CMAKE_INSTALL_INCLUDEDIR})
```

Are all are non-standard patterns and will defeat standard CMake installation.

`CMAKE_PREFIX_PATH` should be set externally and if it must be set internally it should be added to, not reset.  (Or, is this also a "cumulative" setting?)

`CMAKE_INSTALL_PREFIX` should also be set externally and then CMake automatically follows it.

Instead of breaking standards by assuming some kind of source and installation layout, each package should have its `CMakeLists.txt` be stand-alone with these externalities unspecified.

Then a dev environment can be trivially created with a top-level `CMakeLists.txt` file like:

``` cmake
cmake_minimum_required(VERSION 3.12)
project(mydev)
add_subdirectory(appfwk)
add_subdirectory(listrev)
```
And, the developer has these easy commands:

``` cmake
$ export CMAKE_PREFIX_PATH=....
$ cmake -B build -S . -DCMAKE_INSTALL_PREFIX=/my/install 
$ cmake --build build -j$(nproc)
$ cmake --build -t install
$ cmake --build -t clean
```
If there is reason to use the source/install patterns currently backed in to the CMake in this branch, they can still be expressed by filling in the two `CMAKE_` env vars above.  Since we have a script-based install/development, this would be very natural.  The script could even manage creation and updating of the top-level `CMakeLists.txt` file.


PS: unrelated, but at this weeks HSF packaging working group meeting I learned we should be "spelling" all our minimum required cmake version lines with a range of versions like:

``` cmake
cmake_minimum_required(VERSION 3.4...3.12)
```
