### ISSUE TITLE
Splitting environment setup from build scripts

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-buildtools#5]
This is just a placeholder not to forget, will elaborate later.
Please bear with me John...

**Comment by jcfreeman2** [comment]
How about this:

* User sources a standard script so that the dependencies get set up (Boost, cetlib, etc.)
<pre>
. setup_build_environment
</pre>

* User executes `build_daq_software.sh` which will skip the config+generate stage and jump right to the build stage unless one of the following two things are true:
1. `./build/CMakeCache.txt` doesn't exist (this was Eric's innovation for the now-closed daq-buildtools pull request #6 )
2. User provides the `--clean` option, which will blow away the contents of `./build`, and then execute the config+generate stage followed by the build stage. 
 
And for completeness' sake here, it might be nice if users could provide a `--unittest` option which will run all the unit tests available

**Comment by alessandrothea** [comment]
Hi John,

Thanks for not waiting for me to fill the ticket :) 
This looks good
* `setup_build_environment`: works for me
* `build_daq_software.sh`: sounds good to me, including the `--clean` and `--unittest` options.
   in line with what Kurt asked on the chat, can you list the equivalent `build_daq_software.sh` bare command-line commands? 

Thanks!

**Comment by jcfreeman2** [comment]
Say you''re already in your build directory, `./build`. Then, the following bare command-line commands are the main focus of each call:
```
build_daq_software.sh
```
means
```
cmake --build . # Assuming CMakeCache already there. Equivalent to "make" when we're using Unix Makefiles and not, say, Ninja
```
And
```
build_daq_software.sh --clean
```
means
```
rm -rf *
cmake ..  
cmake --build .
```
And adding the unittest option might be as simple as just seeking out all executables in subdirectories called unittest and calling them with the ` -l all` argument, so output is maximally printed to screen.
