### ISSUE TITLE
Problem with simultaneous build on Nevis server

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-buildtools#54]
Just finished a discussion with Lukas Arnold; it seems he's having trouble building multiple repositories at once on his server at Nevis, a problem which hasn't appeared on, e.g., lxplus. To build `daq-buildtools` + `cmdlib` + `appfwk`, he needs to build each package separately with `build_daq_software.sh`, in that order. The call to `daq_add_subpackages` in `sourcecode/CMakeLists.txt` should mean that this isn't necessary, and it fact it's clear that on some level the build system knows the correct order to process the packages ("`-- Package build order: daq-buildtools;cmdlib;appfwk`") but if multiple repositories are tried the system won't run cmake on daq-buildtools first, so `find_package(daq-buildtools)` in cmdlib fails.

**Comment by philiprodrigues** [comment]
Lukas's issue reminded me that I had seen something similar in my build attempts, so I went back and tried to track it down. I find that the build fails when the `CMAKE_PREFIX_PATH` environment variable is set before sourcing `setup_build_environment`, and I think the reason is this:

`setup_build_environment` has:

```
export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$DBT_INSTALL_DIR/lib64:$DBT_INSTALL_DIR/lib
```

When `CMAKE_PREFIX_PATH` is initially empty, this results in the new variable beginning in a colon. The setups of various ups products which follow modify  `CMAKE_PREFIX_PATH` so that it eventually contains an empty path (ie, there are two colons in a row). Apparently cmake interprets the empty entry to mean "the current directory", which is the `build/` directory when cmake is run by `build_daq_software.sh`. It's under this build directory that cmake finds the `daq-buildtoolsConfig.cmake` file.

When `CMAKE_PREFIX_PATH` is initially nonempty, there's no double-colon in the final value of the variable, and so the current directory is not searched.

This explanation sounds a bit crazy, but two further tests make me think it's correct:

* Running `cmake` manually from the main test release directory (ie, the one containing `setup_build_environment`) fails in the same way

* Setting `CMAKE_PREFIX_PATH=::a` (say) before sourcing `setup_build_environment` results in the build (with `build_daq_software.sh`) working, because now the current directory is in the path again.

Anyway, I think the solution is to explicitly add the build directory to `CMAKE_PREFIX_PATH`

**Comment by jcfreeman2** [comment]
@philiprodrigues Thanks for looking in to this. I wasn't able to get the multi-repository build to fail after setting CMAKE_PREFIX_PATH so it didn't get the double colon, but then, I was working on a Fermilab system where I hadn't seen Lukas's problem before. In case you've seen the failure on a system I have access to, please let me know. Also, I've pointed Lukas to your solution and given him a couple of tips on how to test it.

**Comment by philiprodrigues** [comment]
This script demonstrates the failure for me on `dunegpvm11` (you can find a copy in `/dune/app/users/rodriges/tmp/run-build-test.sh`):

```bash
#!/bin/bash

# Set CMAKE_PREFIX_PATH to something. This seems to cause the build to fail
export CMAKE_PREFIX_PATH=a

curl -O https://raw.githubusercontent.com/DUNE-DAQ/daq-buildtools/v1.2.1/bin/quick-start.sh
chmod +x quick-start.sh
./quick-start.sh
cd sourcecode
git clone https://github.com/DUNE-DAQ/appfwk.git
git clone https://github.com/DUNE-DAQ/cmdlib.git
cd ..
. ./setup_build_environment
./build_daq_software.sh --install
(none) dunegpvm11:/dune/app/users/```

**Comment by jcfreeman2** [comment]
@philiprodrigues This is a bit odd...logged in to `dunegpvm11.fnal.gov`, `/dune/app/users/rodriges/tmp/run-build-test.sh` works fine; this is regardless of whether I source (/nashome/j/jcfree/daqbuild_CMAKE_PREFIX_PATH2) or execute it (/nashome/j/jcfree/daqbuild_CMAKE_PREFIX_PATH3).

**Comment by jcfreeman2** [comment]
And just to confirm, both times I did this off a fresh login.

**Comment by philiprodrigues** [comment]
Hm, strange. I get the same failure when I move my `.bashrc` out of the way (so that hopefully my environment is minimal). Since I'm able to build the software when I need to, maybe we just wait to hear back from Lukas? Or I'm happy to try anything else you can suggest; I'm a little out of ideas myself.

**Comment by alessandrothea** [comment]
Hi, I didn't mean re-open the issue.
While we're at it I have to admit that I fail to understand how 
```sh
export PATH=".:${PATH}"
```

mitigates the isse from Lukas

**Comment by philiprodrigues** [comment]
CMake searches in `$PATH` in the same way it searches in `$CMAKE_PREFIX_PATH`, so the same analysis I gave above holds for `$PATH`

(This fact is rather hidden by the cmake docs, but it's on this page:

https://cmake.org/cmake/help/latest/command/find_package.html

Search for: "Search the standard system environment variables")

**Comment by alessandrothea** [comment]
Thanks. Now, if the solution is ensuring that `build/` is in `CMAKE_PREFIX_PATH`, it is advisable to explicitly do that rather than using `PATH` as a proxy.

I think I stumbled on the same issue during the recent package refactoring, and my solution has been forcing `CMAKE_CURRENT_BINARY_DIR` (i.e. `build`) into the `CMAKE_PREFIX_PATH` in the top-level `CMakeLists.txt` file.

https://github.com/DUNE-DAQ/daq-buildtools/blob/bff360ddc979b2b1d234b1a06ff9b3e3f3f11b3d/configs/CMakeLists.txt#L9

This seems appropriate as it is a specific setting of this buildtools environment.
Can you confirm if this alternative approach solves the original problem? If so I'd rather remove the current directory from PATH.

**Comment by philiprodrigues** [comment]
I agree that setting `CMAKE_PREFIX_PATH` is better in this case than setting `PATH`. Your change to the top-level `CMakeLists.txt` seems to work for me.
